// Known-answer vectors for gcm_init_v8 (12 vectors).
//
// Each vector fixes a 128-bit key H (words H[0]:H[1]) and the twisted
// powers H^1..H^8 that gcm_init_v8 must store, in its own word order.
// The expected values were generated by the verbatim aws-lc reference
// gcm_init_nohw + gcm_polyval_nohw (see ref_gcm_nohw.c), NOT by
// gcm_init_v8 itself. Included inside test_known_values_gcm_init_v8().
//
// Origin: input keys are porter-chosen diverse values (one is the
// McGrew-Viega/NIST zero-key GHASH subkey H); expected outputs are the
// GHASH-field powers of H per aws-lc gcm_nohw.c @ 2df1601d7.

// Vector 1: H = 0 (degenerate zero key)
{ static const uint64_t Hin[2] = {0x0000000000000000ULL,0x0000000000000000ULL};
  static const uint64_t exp[16] = {
    0x0000000000000000ULL,0x0000000000000000ULL, // H^1
    0x0000000000000000ULL,0x0000000000000000ULL, // H^2
    0x0000000000000000ULL,0x0000000000000000ULL, // H^3
    0x0000000000000000ULL,0x0000000000000000ULL, // H^4
    0x0000000000000000ULL,0x0000000000000000ULL, // H^5
    0x0000000000000000ULL,0x0000000000000000ULL, // H^6
    0x0000000000000000ULL,0x0000000000000000ULL, // H^7
    0x0000000000000000ULL,0x0000000000000000ULL // H^8
  };
  if (gcm_init_v8_kat_check(1, Hin, exp)) ++failures; else ++successes; }

// Vector 2: H = 1 in the low word
{ static const uint64_t Hin[2] = {0x0000000000000000ULL,0x0000000000000001ULL};
  static const uint64_t exp[16] = {
    0x0000000000000000ULL,0x0000000000000002ULL, // H^1
    0x0e10000000000000ULL,0x0000000000000007ULL, // H^2
    0xe138400000000000ULL,0x000000000000000aULL, // H^3
    0xa400010000000000ULL,0x000000000000001aULL, // H^4
    0x3840038400000000ULL,0x0000000000000022ULL, // H^5
    0xbb11054010000000ULL,0x0000000000000077ULL, // H^6
    0x35efc97538400000ULL,0x00000000000000a2ULL, // H^7
    0xab00000000010000ULL,0x00000000000001b5ULL // H^8
  };
  if (gcm_init_v8_kat_check(2, Hin, exp)) ++failures; else ++successes; }

// Vector 3: H = 1 in the high word
{ static const uint64_t Hin[2] = {0x0000000000000001ULL,0x0000000000000000ULL};
  static const uint64_t exp[16] = {
    0x0000000000000002ULL,0x0000000000000000ULL, // H^1
    0x0000000000000000ULL,0x0000000000000004ULL, // H^2
    0x000000000000000eULL,0x1000000000000000ULL, // H^3
    0x3840000000000000ULL,0x000000000000001cULL, // H^4
    0x000000000000002aULL,0x0080000000000000ULL, // H^5
    0x01c2000000000000ULL,0x0000000000000054ULL, // H^6
    0x00000000000000d7ULL,0x5384000000000000ULL, // H^7
    0xdc00100000000000ULL,0x00000000000001aeULL // H^8
  };
  if (gcm_init_v8_kat_check(3, Hin, exp)) ++failures; else ++successes; }

// Vector 4: H high bit set (exercises the shift-and-reduce carry)
{ static const uint64_t Hin[2] = {0x8000000000000000ULL,0x0000000000000000ULL};
  static const uint64_t exp[16] = {
    0xc200000000000000ULL,0x0000000000000001ULL, // H^1
    0xc200000000000000ULL,0x0000000000000001ULL, // H^2
    0xc200000000000000ULL,0x0000000000000001ULL, // H^3
    0xc200000000000000ULL,0x0000000000000001ULL, // H^4
    0xc200000000000000ULL,0x0000000000000001ULL, // H^5
    0xc200000000000000ULL,0x0000000000000001ULL, // H^6
    0xc200000000000000ULL,0x0000000000000001ULL, // H^7
    0xc200000000000000ULL,0x0000000000000001ULL // H^8
  };
  if (gcm_init_v8_kat_check(4, Hin, exp)) ++failures; else ++successes; }

// Vector 5: H all ones
{ static const uint64_t Hin[2] = {0xffffffffffffffffULL,0xffffffffffffffffULL};
  static const uint64_t exp[16] = {
    0x3dffffffffffffffULL,0xffffffffffffffffULL, // H^1
    0x2a05555555555555ULL,0x5555555555555555ULL, // H^2
    0xd2fd599999999999ULL,0x9999999999999999ULL, // H^3
    0xb3ffffeeeeeeeeeeULL,0xeeeeeeeeeeeeeeeeULL, // H^4
    0xa095555de1e1e1e1ULL,0xe1e1e1e1e1e1e1e1ULL, // H^5
    0x5333666222727272ULL,0x7272727272727272ULL, // H^6
    0x5c2df7b996be7e7eULL,0x7e7e7e7e7e7e7e7eULL, // H^7
    0xf996969696969797ULL,0x9797979797979797ULL // H^8
  };
  if (gcm_init_v8_kat_check(5, Hin, exp)) ++failures; else ++successes; }

// Vector 6: H = AES-128(0^128) with the zero key (McGrew-Viega / NIST GCM test H)
{ static const uint64_t Hin[2] = {0x66e94bd4ef8a2c3bULL,0x884cfa59ca342b2eULL};
  static const uint64_t exp[16] = {
    0xcdd297a9df145877ULL,0x1099f4b39468565cULL, // H^1
    0x88d320376963120dULL,0xea0b3a488cb9209bULL, // H^2
    0x8695e702c322faf9ULL,0x35c1a04f8bfb2395ULL, // H^3
    0x568bd97348bd9145ULL,0xe4adc23e440c7165ULL, // H^4
    0xf9151b1f632d10b4ULL,0x7d845b630bb0a55dULL, // H^5
    0xec87cfb0e19d1c4eULL,0x4af32418184aee1eULL, // H^6
    0x7d1998bcfc545474ULL,0xf109e6e0b31d1eeeULL, // H^7
    0xd0e417a05fe61ba4ULL,0xa47c653dfbeac924ULL // H^8
  };
  if (gcm_init_v8_kat_check(6, Hin, exp)) ++failures; else ++successes; }

// Vector 7: H = 0x0123456789abcdef : 0xfedcba9876543210
{ static const uint64_t Hin[2] = {0x0123456789abcdefULL,0xfedcba9876543210ULL};
  static const uint64_t exp[16] = {
    0x02468acf13579bdfULL,0xfdb97530eca86420ULL, // H^1
    0x6a03042f18b3b49fULL,0x6ac1c6edda71765dULL, // H^2
    0xe24d38684c9c401cULL,0x61d8cd423c14462bULL, // H^3
    0x445fe4a4aeab4790ULL,0x0e55d7ee9de174daULL, // H^4
    0x5208be99a1beafd5ULL,0x5ec062d3f35ee5f7ULL, // H^5
    0x3239bf43e98d6a67ULL,0x1ef6e08e2c3b2e2eULL, // H^6
    0x1df82769a9ad00a3ULL,0xff29f9891c3f528dULL, // H^7
    0xff6ba4aadb68c5d3ULL,0x9d7b4decc8e30c15ULL // H^8
  };
  if (gcm_init_v8_kat_check(7, Hin, exp)) ++failures; else ++successes; }

// Vector 8: H = 0xfedcba9876543210 : 0x0123456789abcdef
{ static const uint64_t Hin[2] = {0xfedcba9876543210ULL,0x0123456789abcdefULL};
  static const uint64_t exp[16] = {
    0x3fb97530eca86420ULL,0x02468acf13579bdfULL, // H^1
    0x4006517a4de6e1caULL,0x3f9493b88f242308ULL, // H^2
    0xcfb44eb880cd5194ULL,0x154f7a6cf1bb565dULL, // H^3
    0xf7a01b4a4045a97eULL,0xe0bb3900730f9a34ULL, // H^4
    0x6582100b4e5e215bULL,0x4e200cbd03418b79ULL, // H^5
    0x1acebb5a60c9d604ULL,0x8a6be46d46f8749fULL, // H^6
    0xf8aa9c280e33c62bULL,0x578292180db72c19ULL, // H^7
    0x06fd323c4dfe5244ULL,0x0aecda7b5f749b82ULL // H^8
  };
  if (gcm_init_v8_kat_check(8, Hin, exp)) ++failures; else ++successes; }

// Vector 9: H = 0xdeadbeefcafebabe : 0x0f1e2d3c4b5a6978
{ static const uint64_t Hin[2] = {0xdeadbeefcafebabeULL,0x0f1e2d3c4b5a6978ULL};
  static const uint64_t exp[16] = {
    0x7f5b7ddf95fd757cULL,0x1e3c5a7896b4d2f1ULL, // H^1
    0x86f8bfe3a8c4c3cfULL,0xb0480b075874773bULL, // H^2
    0x5469dbaf976af312ULL,0x69e9c7377fbe2deeULL, // H^3
    0x4b4a4910c5231e1fULL,0xb3d2cae66af5bce9ULL, // H^4
    0xe951a557f8983d1cULL,0x9c56f1ff3314c5cdULL, // H^5
    0xdd193d987fffa885ULL,0xb1950865fa6008c7ULL, // H^6
    0x172f5d8cb618f236ULL,0x0aab19c7fe4a66e5ULL, // H^7
    0x150db7217496e2b3ULL,0x634ee6729572ca8cULL // H^8
  };
  if (gcm_init_v8_kat_check(9, Hin, exp)) ++failures; else ++successes; }

// Vector 10: H = 0x952b2a56a5604ac0 : 0xb41f3d5f4b9a2b8d
{ static const uint64_t Hin[2] = {0x952b2a56a5604ac0ULL,0xb41f3d5f4b9a2b8dULL};
  static const uint64_t exp[16] = {
    0xe85654ad4ac09581ULL,0x683e7abe9734571bULL, // H^1
    0x320c97b5a38dba70ULL,0xc91cbcd67ce9abb5ULL, // H^2
    0xf5e15067fbc1e3bdULL,0xc906feabd02e0873ULL, // H^3
    0xc39143fe97338868ULL,0x76838b8870ba2957ULL, // H^4
    0xe35418ab6572bcfaULL,0xc7041bc509f6a745ULL, // H^5
    0xa5d4161a5301cbebULL,0x72275762fc75dfbdULL, // H^6
    0xa89826af3b4cf644ULL,0x0fec4471d0595295ULL, // H^7
    0xeea01987aaf36fa4ULL,0xdbff7338cf394bb8ULL // H^8
  };
  if (gcm_init_v8_kat_check(10, Hin, exp)) ++failures; else ++successes; }

// Vector 11: H = 0xa1b2c3d4e5f60718 : 0x293a4b5c6d7e8f90
{ static const uint64_t Hin[2] = {0xa1b2c3d4e5f60718ULL,0x293a4b5c6d7e8f90ULL};
  static const uint64_t exp[16] = {
    0x816587a9cbec0e30ULL,0x527496b8dafd1f21ULL, // H^1
    0xcfe006e7114c1a7bULL,0xbd50b65763fc6809ULL, // H^2
    0x646b88f02af2c15eULL,0x8e19f71ca611c665ULL, // H^3
    0x55762be2764561edULL,0xf02fb056ba1c9534ULL, // H^4
    0xa546b4ab83a3f29bULL,0x771f876ebb5830e1ULL, // H^5
    0xcebfbdf66830beaeULL,0xd3d77cc7feba2261ULL, // H^6
    0x3d8893263595c706ULL,0xa890a52682970a73ULL, // H^7
    0x433b1276180f49fdULL,0x4b2999bfc55eb087ULL // H^8
  };
  if (gcm_init_v8_kat_check(11, Hin, exp)) ++failures; else ++successes; }

// Vector 12: H = 0x0f0e0d0c0b0a0908 : 0x0706050403020100
{ static const uint64_t Hin[2] = {0x0f0e0d0c0b0a0908ULL,0x0706050403020100ULL};
  static const uint64_t exp[16] = {
    0x1e1c1a1816141210ULL,0x0e0c0a0806040200ULL, // H^1
    0x013fa93ca1338930ULL,0x810f290c21030900ULL, // H^2
    0x000b193c3918199fULL,0x9d981e16e9caaf08ULL, // H^3
    0x7080c73f2938473cULL,0xe308c7038a304700ULL, // H^4
    0xf1a3246dc66dca74ULL,0x308c0b1289ec0c30ULL, // H^5
    0x902f137780e8ac89ULL,0x46982f97fea32b25ULL, // H^6
    0x1fdd381db6d02bd9ULL,0x6a999b37f370a12fULL, // H^7
    0x7eae8a70bcafef53ULL,0xbeb68b8a0c2fef50ULL // H^8
  };
  if (gcm_init_v8_kat_check(12, Hin, exp)) ++failures; else ++successes; }

